---
name: default
type: docker
kind: pipeline

trigger:
  ref:
    - refs/heads/master
    - refs/heads/dev
    - refs/heads/bg-*
    - refs/heads/ch-*
    - refs/heads/ft-*
    - refs/heads/rf-*

steps:
  - name: install
    image: elixir:1.10-alpine
    volumes:
      - name: cache
        path: /root
    commands:
      - mix local.rebar --force
      - mix local.hex --force --if-missing
      - mix deps.get

  - name: test
    image: elixir:1.10-alpine
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_USERNAME: root
      DB_DATABASE: test
      DB_PASSWORD: ""
      MIX_ENV: test
    volumes:
      - name: cache
        path: /root
    commands:
      - mix test

  - name: publish
    image: plugins/docker
    pull: if-not-exists
    settings:
      repo: dorkng/drone-review-app
      auto_tag: true
      dockerfile: docker/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      ref:
      - refs/heads/master
      - refs/tags/*

  - name: manifest
    image: plugins/manifest
    settings:
      spec: docker/manifest.tmpl
      auto_tag: true
      ignore_missing: true
      password:
        from_secret: docker_password
      username:
        from_secret: docker_username
    when:
      ref:
      - refs/heads/master
      - refs/tags/*

volumes:
- name: cache
  temp: {}

services:
  - name: mysql
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: test
