---
name: default
type: docker
kind: pipeline

trigger:
  ref:
    - refs/heads/dev
    - refs/heads/bg-*
    - refs/heads/ch-*
    - refs/heads/ft-*
    - refs/heads/rf-*

steps:
  - name: install-hex
    image: elixir
    volumes:
      - name: cache
        path: /root
    commands:
      - mix local.rebar --force
      - mix local.hex --force --if-missing

  - name: install
    image: elixir
    volumes:
      - name: cache
        path: /root
    commands:
      - mix deps.get

  - name: test
    image: elixir
    volumes:
      - name: cache
        path: /root
    commands:
      - mix test

  - name: build
    image: elixir
    volumes:
      - name: cache
        path: /root
    commands:
      - mix escript.build

volumes:
- name: cache
  temp: {}